const quizData = [
  // PART 1: INORGANIC AND SIMPLE HYBRIDIZATION
  { id: "q1", title: "1. Halogen Acids (Atomic Size)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "hf", name: "HF", smiles: "F", rank: 1 }, { id: "hcl", name: "HCl", smiles: "Cl", rank: 2 }, { id: "hbr", name: "HBr", smiles: "Br", rank: 3 }, { id: "hi", name: "HI", smiles: "I", rank: 4 } ] },
  { id: "q2", title: "2. Electronegativity (Period 2 Hydrides)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "ch4", name: "Methane", smiles: "C", rank: 1 }, { id: "nh3", name: "Ammonia", smiles: "N", rank: 2 }, { id: "h2o", name: "Water", smiles: "O", rank: 3 }, { id: "hf2", name: "HF", smiles: "F", rank: 4 } ] },
  { id: "q3", title: "3. s-Character & Hybridization", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "ethane", name: "Ethane", smiles: "CC", rank: 1 }, { id: "ethene", name: "Ethene", smiles: "C=C", rank: 2 }, { id: "ethyne", name: "Ethyne", smiles: "C#C", rank: 3 } ] },
  { id: "q4", title: "4. Alcohols, Water, Alkynes", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "ammonia", name: "Ammonia", smiles: "N", rank: 1 }, { id: "ethyne", name: "Ethyne", smiles: "C#C", rank: 2 }, { id: "ethanol", name: "Ethanol", smiles: "CCO", rank: 3 }, { id: "water", name: "Water", smiles: "O", rank: 4 } ] },
  
  // PART 2: HALOFORMS AND SIMPLE -I EFFECTS
  { id: "q5", title: "5. Haloforms (Backbonding vs -I)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "chf3", name: "Fluoroform", smiles: "FC(F)F", rank: 1 }, { id: "chi3", name: "Iodoform", smiles: "IC(I)I", rank: 2 }, { id: "chbr3", name: "Bromoform", smiles: "BrC(Br)Br", rank: 3 }, { id: "chcl3", name: "Chloroform", smiles: "ClC(Cl)Cl", rank: 4 } ] },
  { id: "q6", title: "6. Primary Alcohols (+I Effect of Alkyl)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "tbut", name: "tert-Butanol", smiles: "CC(C)(C)O", rank: 1 }, { id: "iso", name: "Isopropanol", smiles: "CC(C)O", rank: 2 }, { id: "eth", name: "Ethanol", smiles: "CCO", rank: 3 }, { id: "meth", name: "Methanol", smiles: "CO", rank: 4 } ] },
  { id: "q7", title: "7. Fluorinated Alcohols (-I Effect Number)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "monof", name: "2-Fluoroethanol", smiles: "FCCO", rank: 1 }, { id: "dif", name: "2,2-Difluoroethanol", smiles: "FC(F)CO", rank: 2 }, { id: "trif", name: "2,2,2-Trifluoroethanol", smiles: "FC(F)(F)CO", rank: 3 } ] },

  // PART 3: CARBOXYLIC ACIDS AND DISTANCE EFFECTS
  { id: "q8", title: "8. Halogenated Butyric Acids (Distance)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "butyric", name: "Butyric Acid", smiles: "CCCC(=O)O", rank: 1 }, { id: "gammaf", name: "γ-Fluorobutyric acid", smiles: "FCCCC(=O)O", rank: 2 }, { id: "betaf", name: "β-Fluorobutyric acid", smiles: "CC(F)CC(=O)O", rank: 3 }, { id: "alphaf", name: "α-Fluorobutyric acid", smiles: "CCCC(F)C(=O)O", rank: 4 } ] },
  { id: "q9", title: "9. Halogen Type in Carboxylic Acids (-I)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "acetic", name: "Acetic Acid", smiles: "CC(=O)O", rank: 1 }, { id: "iodo", name: "Iodoacetic acid", smiles: "ICC(=O)O", rank: 2 }, { id: "bromo", name: "Bromoacetic acid", smiles: "BrCC(=O)O", rank: 3 }, { id: "chloro", name: "Chloroacetic acid", smiles: "ClCC(=O)O", rank: 4 }, { id: "fluoro", name: "Fluoroacetic acid", smiles: "FCC(=O)O", rank: 5 } ] },
  { id: "q10", title: "10. Number of Halogens on Acetic Acid", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "acetic", name: "Acetic Acid", smiles: "CC(=O)O", rank: 1 }, { id: "chloro1", name: "Chloroacetic", smiles: "ClCC(=O)O", rank: 2 }, { id: "chloro2", name: "Dichloroacetic", smiles: "ClC(Cl)C(=O)O", rank: 3 }, { id: "chloro3", name: "Trichloroacetic", smiles: "ClC(Cl)(Cl)C(=O)O", rank: 4 } ] },
  
  // PART 4: DICARBOXYLIC ACIDS
  { id: "q11", title: "11. Dicarboxylic Acids (Distance, pKa1)", description: "Rank acidic strength (pKa1) from WEAKEST to STRONGEST:", items: [ { id: "adipic", name: "Adipic Acid", smiles: "O=C(O)CCCCC(=O)O", rank: 1 }, { id: "succinic", name: "Succinic Acid", smiles: "O=C(O)CCC(=O)O", rank: 2 }, { id: "malonic", name: "Malonic Acid", smiles: "O=C(O)CC(=O)O", rank: 3 }, { id: "oxalic", name: "Oxalic Acid", smiles: "O=C(O)C(=O)O", rank: 4 } ] },
  { id: "q12", title: "12. Dicarboxylic Acids (pKa2)", description: "Rank acidic strength (pKa2) from WEAKEST to STRONGEST:", items: [ { id: "oxalic2", name: "Oxalic Acid", smiles: "O=C(O)C(=O)O", rank: 1 }, { id: "malonic2", name: "Malonic Acid", smiles: "O=C(O)CC(=O)O", rank: 2 }, { id: "succinic2", name: "Succinic Acid", smiles: "O=C(O)CCC(=O)O", rank: 3 } ] },

  // PART 5: PHENOLS (SUBSTITUENT EFFECTS)
  { id: "q13", title: "13. Phenols: Methyl groups (+I, +H)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "pcresol", name: "p-Cresol", smiles: "Cc1ccc(O)cc1", rank: 1 }, { id: "mcresol", name: "m-Cresol", smiles: "Cc1cccc(O)c1", rank: 2 }, { id: "phenol", name: "Phenol", smiles: "c1ccccc1O", rank: 3 } ] },
  { id: "q14", title: "14. Phenols: Nitro groups (-M, -I)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "phenoln", name: "Phenol", smiles: "c1ccccc1O", rank: 1 }, { id: "mnitro", name: "m-Nitrophenol", smiles: "O=N(=O)c1cccc(O)c1", rank: 2 }, { id: "pnitro", name: "p-Nitrophenol", smiles: "O=N(=O)c1ccc(O)cc1", rank: 3 }, { id: "onitro", name: "o-Nitrophenol", smiles: "O=N(=O)c1ccccc1O", rank: 4 } ] },
  { id: "q15", title: "15. Phenols: Multiple Nitro groups", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "mnitro", name: "m-Nitrophenol", smiles: "O=N(=O)c1cccc(O)c1", rank: 1 }, { id: "pnitro", name: "p-Nitrophenol", smiles: "O=N(=O)c1ccc(O)cc1", rank: 2 }, { id: "24dinitro", name: "2,4-Dinitrophenol", smiles: "O=N(=O)c1ccc(O)c(N(=O)=O)c1", rank: 3 }, { id: "picric", name: "Picric Acid", smiles: "Oc1c(N(=O)=O)cc(N(=O)=O)cc1N(=O)=O", rank: 4 } ] },
  { id: "q16", title: "16. Phenols: Methoxy groups (+M, -I)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "pmethoxy", name: "p-Methoxyphenol (+M > -I)", smiles: "COc1ccc(O)cc1", rank: 1 }, { id: "phenol", name: "Phenol", smiles: "c1ccccc1O", rank: 2 }, { id: "mmethoxy", name: "m-Methoxyphenol (-I only)", smiles: "COc1cccc(O)c1", rank: 3 } ] },
  { id: "q17", title: "17. Phenols: Halogens (-I > +M)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "phenol", name: "Phenol", smiles: "c1ccccc1O", rank: 1 }, { id: "pfluoro", name: "p-Fluorophenol", smiles: "Fc1ccc(O)cc1", rank: 2 }, { id: "pchloro", name: "p-Chlorophenol", smiles: "Clc1ccc(O)cc1", rank: 3 }, { id: "pbromo", name: "p-Bromophenol", smiles: "Brc1ccc(O)cc1", rank: 4 } ] },
  { id: "q18", title: "18. Phenols: Cyano groups (-M, -I)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "phenol", name: "Phenol", smiles: "c1ccccc1O", rank: 1 }, { id: "mcyano", name: "m-Cyanophenol", smiles: "N#Cc1cccc(O)c1", rank: 2 }, { id: "pcyano", name: "p-Cyanophenol", smiles: "N#Cc1ccc(O)cc1", rank: 3 } ] },
  
  // PART 6: BENZOIC ACIDS
  { id: "q19", title: "19. Benzoic Acids: Nitro groups", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "benzoic", name: "Benzoic Acid", smiles: "O=C(O)c1ccccc1", rank: 1 }, { id: "mnitrob", name: "m-Nitrobenzoic", smiles: "O=N(=O)c1cccc(C(=O)O)c1", rank: 2 }, { id: "pnitrob", name: "p-Nitrobenzoic", smiles: "O=N(=O)c1ccc(C(=O)O)cc1", rank: 3 }, { id: "onitrob", name: "o-Nitrobenzoic", smiles: "O=N(=O)c1ccccc1C(=O)O", rank: 4 } ] },
  { id: "q20", title: "20. Benzoic Acids: Methyl groups (+I, +H)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "ptoluic", name: "p-Toluic", smiles: "Cc1ccc(C(=O)O)cc1", rank: 1 }, { id: "mtoluic", name: "m-Toluic", smiles: "Cc1cccc(C(=O)O)c1", rank: 2 }, { id: "benzoic", name: "Benzoic Acid", smiles: "O=C(O)c1ccccc1", rank: 3 }, { id: "otoluic", name: "o-Toluic (Ortho Effect)", smiles: "Cc1ccccc1C(=O)O", rank: 4 } ] },
  { id: "q21", title: "21. Benzoic Acids: Halogens (-I > +M)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "benzoic", name: "Benzoic Acid", smiles: "O=C(O)c1ccccc1", rank: 1 }, { id: "pchlorob", name: "p-Chlorobenzoic", smiles: "Clc1ccc(C(=O)O)cc1", rank: 2 }, { id: "mchlorob", name: "m-Chlorobenzoic", smiles: "Clc1cccc(C(=O)O)c1", rank: 3 }, { id: "ochlorob", name: "o-Chlorobenzoic", smiles: "Clc1ccccc1C(=O)O", rank: 4 } ] },
  { id: "q22", title: "22. Benzoic Acids: Methoxy groups", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "panisic", name: "p-Anisic Acid", smiles: "COc1ccc(C(=O)O)cc1", rank: 1 }, { id: "benzoic", name: "Benzoic Acid", smiles: "O=C(O)c1ccccc1", rank: 2 }, { id: "manisic", name: "m-Methoxybenzoic", smiles: "COc1cccc(C(=O)O)c1", rank: 3 }, { id: "oanisic", name: "o-Anisic Acid (Ortho)", smiles: "COc1ccccc1C(=O)O", rank: 4 } ] },
  { id: "q23", title: "23. Benzoic vs Aliphatic Acids", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "acetic", name: "Acetic Acid", smiles: "CC(=O)O", rank: 1 }, { id: "propanoic", name: "Propanoic Acid", smiles: "CCC(=O)O", rank: 2 }, { id: "benzoic", name: "Benzoic Acid", smiles: "O=C(O)c1ccccc1", rank: 3 }, { id: "formic", name: "Formic Acid", smiles: "O=CO", rank: 4 } ] },
  
  // PART 7: BASICITY OF AMINES (ALIPHATIC)
  { id: "q24", title: "24. Aqueous Phase Basicity (Ethylamines)", description: "Rank basicity from WEAKEST to STRONGEST (Aqueous):", items: [ { id: "ammonia", name: "Ammonia", smiles: "N", rank: 1 }, { id: "3deg", name: "Triethylamine", smiles: "CCN(CC)CC", rank: 2 }, { id: "1deg", name: "Ethylamine", smiles: "CCN", rank: 3 }, { id: "2deg", name: "Diethylamine", smiles: "CCNCC", rank: 4 } ] },
  { id: "q25", title: "25. Aqueous Phase Basicity (Methylamines)", description: "Rank basicity from WEAKEST to STRONGEST (Aqueous):", items: [ { id: "ammonia", name: "Ammonia", smiles: "N", rank: 1 }, { id: "3deg", name: "Trimethylamine", smiles: "CN(C)C", rank: 2 }, { id: "1deg", name: "Methylamine", smiles: "CN", rank: 3 }, { id: "2deg", name: "Dimethylamine", smiles: "CNC", rank: 4 } ] },
  { id: "q26", title: "26. Gaseous Phase Basicity", description: "Rank basicity from WEAKEST to STRONGEST (Gas Phase):", items: [ { id: "ammonia", name: "Ammonia", smiles: "N", rank: 1 }, { id: "1deg", name: "Methylamine", smiles: "CN", rank: 2 }, { id: "2deg", name: "Dimethylamine", smiles: "CNC", rank: 3 }, { id: "3deg", name: "Trimethylamine", smiles: "CN(C)C", rank: 4 } ] },
  { id: "q27", title: "27. Steric Hindrance in Amines", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "triphenyl", name: "Triphenylamine", smiles: "c1ccc(N(c2ccccc2)c3ccccc3)cc1", rank: 1 }, { id: "diphenyl", name: "Diphenylamine", smiles: "c1ccc(Nc2ccccc2)cc1", rank: 2 }, { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 3 }, { id: "alkyl", name: "Cyclohexylamine", smiles: "NC1CCCCC1", rank: 4 } ] },

  // PART 8: BASICITY OF ANILINES
  { id: "q28", title: "28. Anilines: Nitro groups (-M, -I)", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "pnitro", name: "p-Nitroaniline", smiles: "Nc1ccc(N(=O)=O)cc1", rank: 1 }, { id: "mnitro", name: "m-Nitroaniline", smiles: "Nc1cccc(N(=O)=O)c1", rank: 2 }, { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 3 } ] },
  { id: "q29", title: "29. Anilines: Methyl groups (+I, +H)", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "otol", name: "o-Toluidine (Ortho effect / SIR)", smiles: "Cc1ccccc1N", rank: 1 }, { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 2 }, { id: "mtol", name: "m-Toluidine", smiles: "Cc1cccc(N)c1", rank: 3 }, { id: "ptol", name: "p-Toluidine", smiles: "Cc1ccc(N)cc1", rank: 4 } ] },
  { id: "q30", title: "30. Anilines: Methoxy groups (+M, -I)", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "oanis", name: "o-Anisidine (SIP Effect)", smiles: "COc1ccccc1N", rank: 1 }, { id: "manis", name: "m-Anisidine (-I only)", smiles: "COc1cccc(N)c1", rank: 2 }, { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 3 }, { id: "panis", name: "p-Anisidine (+M > -I)", smiles: "COc1ccc(N)cc1", rank: 4 } ] },
  { id: "q31", title: "31. Anilines: Halogens (-I > +M)", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "ochloro", name: "o-Chloroaniline", smiles: "Clc1ccccc1N", rank: 1 }, { id: "mchloro", name: "m-Chloroaniline", smiles: "Clc1cccc(N)c1", rank: 2 }, { id: "pchloro", name: "p-Chloroaniline", smiles: "Clc1ccc(N)cc1", rank: 3 }, { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 4 } ] },
  { id: "q32", title: "32. N-Substituted Anilines", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 1 }, { id: "nmethyl", name: "N-Methylaniline", smiles: "CNc1ccccc1", rank: 2 }, { id: "ndimethyl", name: "N,N-Dimethylaniline", smiles: "CN(C)c1ccccc1", rank: 3 } ] },
  { id: "q33", title: "33. Steric Inhibition of Resonance (SIR)", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 1 }, { id: "nn", name: "N,N-Dimethylaniline", smiles: "CN(C)c1ccccc1", rank: 2 }, { id: "sir", name: "2,6-Dimethyl-N,N-dimethylaniline", smiles: "Cc1c(N(C)C)c(C)ccc1", rank: 3 } ] },

  // PART 9: ADVANCED / MISCELLANEOUS BASICITY
  { id: "q34", title: "34. Amidines, Amides, Amines", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "amide", name: "Acetamide", smiles: "CC(=O)N", rank: 1 }, { id: "aniline", name: "Aniline", smiles: "Nc1ccccc1", rank: 2 }, { id: "amine", name: "Ethylamine", smiles: "CCN", rank: 3 }, { id: "amidine", name: "Acetamidine", smiles: "CC(=N)N", rank: 4 } ] },
  { id: "q35", title: "35. Guanidines vs Amidines", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "amine", name: "Methylamine", smiles: "CN", rank: 1 }, { id: "amidine", name: "Acetamidine", smiles: "CC(=N)N", rank: 2 }, { id: "guanidine", name: "Guanidine", smiles: "NC(=N)N", rank: 3 } ] },
  { id: "q36", title: "36. Hybridization of Nitrogen", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "cyanide", name: "Acetonitrile (sp)", smiles: "CC#N", rank: 1 }, { id: "pyridine", name: "Pyridine (sp2)", smiles: "c1ccncc1", rank: 2 }, { id: "piperidine", name: "Piperidine (sp3)", smiles: "C1CCNCC1", rank: 3 } ] },
  { id: "q37", title: "37. Pyrole vs Pyridine vs Piperidine", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "pyrrole", name: "Pyrrole", smiles: "c1cc[nH]c1", rank: 1 }, { id: "pyridine", name: "Pyridine", smiles: "c1ccncc1", rank: 2 }, { id: "piperidine", name: "Piperidine", smiles: "C1CCNCC1", rank: 3 } ] },
  { id: "q38", title: "38. Amides vs Amines vs Imines", description: "Rank basicity from WEAKEST to STRONGEST:", items: [ { id: "amide", name: "Acetamide", smiles: "CC(=O)N", rank: 1 }, { id: "imine", name: "Ethylidenemethylamine", smiles: "CC=NC", rank: 2 }, { id: "amine", name: "Diethylamine", smiles: "CCNCC", rank: 3 } ] },
  
  // PART 10: ADVANCED / MISCELLANEOUS ACIDITY
  { id: "q39", title: "39. Ortho effect vs Steric Inhibition of Protonation", description: "Rank acidity from WEAKEST to STRONGEST:", items: [ { id: "p-tert", name: "p-tert-Butylbenzoic Acid", smiles: "CC(C)(C)c1ccc(C(=O)O)cc1", rank: 1 }, { id: "benzoic", name: "Benzoic Acid", smiles: "O=C(O)c1ccccc1", rank: 2 }, { id: "o-tert", name: "o-tert-Butylbenzoic Acid", smiles: "CC(C)(C)c1ccccc1C(=O)O", rank: 3 } ] },
  { id: "q40", title: "40. Terminal Alkynes vs Alkenes vs Alkanes", description: "Rank acidity from WEAKEST to STRONGEST:", items: [ { id: "alkane", name: "Ethane", smiles: "CC", rank: 1 }, { id: "alkene", name: "Ethene", smiles: "C=C", rank: 2 }, { id: "ammonia", name: "Ammonia", smiles: "N", rank: 3 }, { id: "alkyne", name: "Acetylene", smiles: "C#C", rank: 4 } ] },
  { id: "q41", title: "41. Trihalomethanes (Acidity)", description: "Rank acidity from WEAKEST to STRONGEST:", items: [ { id: "fluoro", name: "Fluoroform", smiles: "FC(F)F", rank: 1 }, { id: "iodo", name: "Iodoform", smiles: "IC(I)I", rank: 2 }, { id: "bromo", name: "Bromoform", smiles: "BrC(Br)Br", rank: 3 }, { id: "chloro", name: "Chloroform (-I & d-orbital resonance)", smiles: "ClC(Cl)Cl", rank: 4 } ] },
  { id: "q42", title: "42. Hydration Energy vs Electronegativity", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "sh2", name: "H2S", smiles: "S", rank: 1 }, { id: "h2o", name: "H2O", smiles: "O", rank: 2 }, { id: "hf", name: "HF", smiles: "F", rank: 3 } ] },  // wait, H2S > H2O. H2O=weakest, H2S=middle, HF=strongest.  Correction!
  
  // Wait, let's fix q42:  H2O pKa ~15.7, H2S pKa ~7.0, HF pKa ~3.2. Order H2O < H2S < HF
  // So:
  { id: "q42", title: "42. Group 16 Hydrides vs Halogens", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "h2o", name: "Water", smiles: "O", rank: 1 }, { id: "h2s", name: "Hydrogen Sulfide", smiles: "S", rank: 2 }, { id: "hf", name: "Hydrogen Fluoride", smiles: "F", rank: 3 } ] },

  { id: "q43", title: "43. Sulfonic Acids vs Carboxylic Acids vs Phenols", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "al", name: "Ethanol", smiles: "CCO", rank: 1 }, { id: "ph", name: "Phenol", smiles: "c1ccccc1O", rank: 2 }, { id: "ca", name: "Acetic Acid", smiles: "CC(=O)O", rank: 3 }, { id: "sa", name: "Methanesulfonic Acid", smiles: "CS(=O)(=O)O", rank: 4 } ] },
  { id: "q44", title: "44. Inorganic Acids (Oxoacids of Chlorine)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "hclo", name: "Hypochlorous Acid", smiles: "OCl", rank: 1 }, { id: "hclo2", name: "Chlorous Acid", smiles: "O=Cl(O)", rank: 2 }, { id: "hclo3", name: "Chloric Acid", smiles: "O=Cl(=O)O", rank: 3 }, { id: "hclo4", name: "Perchloric Acid", smiles: "O=Cl(=O)(=O)O", rank: 4 } ] },
  { id: "q45", title: "45. Perhalo Acids (HXO4)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "io4", name: "Periodic Acid", smiles: "O=I(=O)(=O)O", rank: 1 }, { id: "bro4", name: "Perbromic Acid", smiles: "O=Br(=O)(=O)O", rank: 2 }, { id: "clo4", name: "Perchloric Acid", smiles: "O=Cl(=O)(=O)O", rank: 3 } ] },
  
  // ACTIVE METHYLENE / CARBON ACIDS
  { id: "q46", title: "46. Carbon Acids (Active Methylene)", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "acetone", name: "Acetone", smiles: "CC(=O)C", rank: 1 }, { id: "ester", name: "Ethyl Acetoacetate", smiles: "CCOC(=O)CC(=O)C", rank: 2 }, { id: "ketone", name: "Acetylacetone", smiles: "CC(=O)CC(=O)C", rank: 3 } ] },
  { id: "q47", title: "47. Hydrocarbons to Carbon Acids", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "ethane", name: "Ethane", smiles: "CC", rank: 1 }, { id: "ethene", name: "Ethene", smiles: "C=C", rank: 2 }, { id: "toluene", name: "Toluene", smiles: "Cc1ccccc1", rank: 3 }, { id: "cyclopentadiene", name: "Cyclopentadiene (Aromatic anion)", smiles: "C1C=CC=C1", rank: 4 } ] },
  
  // EXCEPTIONAL CASES / REPEATS FROM NOTES
  { id: "q48", title: "48. Picric Acid vs Mineral Acids", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "phenol", name: "Phenol", smiles: "c1ccccc1O", rank: 1 }, { id: "picric", name: "Picric Acid", smiles: "Oc1c(N(=O)=O)cc(N(=O)=O)cc1N(=O)=O", rank: 2 }, { id: "hcl", name: "Hydrochloric Acid", smiles: "Cl", rank: 3 } ] },
  { id: "q49", title: "49. Trichloroacetic vs Trifluoroacetic", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "acetic", name: "Acetic Acid", smiles: "CC(=O)O", rank: 1 }, { id: "dichloro", name: "Dichloroacetic", smiles: "ClC(Cl)C(=O)O", rank: 2 }, { id: "trichloro", name: "Trichloroacetic", smiles: "ClC(Cl)(Cl)C(=O)O", rank: 3 }, { id: "trifluoro", name: "Trifluoroacetic", smiles: "FC(F)(F)C(=O)O", rank: 4 } ] },
  { id: "q50", title: "50. Cyanic vs Isocyanic", description: "Rank acidic strength from WEAKEST to STRONGEST:", items: [ { id: "iso", name: "Isocyanic acid", smiles: "HN=C=O", rank: 1 }, { id: "cyanic", name: "Cyanic acid", smiles: "N#CO", rank: 2 } ] }
];

window.quizData = quizData;
